# Generated by Django 3.2.4 on 2021-06-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="profile_picture",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="web_page",
        ),
        migrations.AlterField(
            model_name="profile",
            name="job",
            field=models.CharField(
                choices=[("Architect", "Architect"), ("Constructor", "Constructor")],
                max_length=20,
            ),
        ),
    ]
