# Generated by Django 3.2.4 on 2021-06-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20210615_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='job',
            field=models.CharField(blank=True, choices=[('Architect', 'Architect'), ('Lecturer/Student', 'Lecturer/Student'), ('Constructor', 'Constructor'), ('Other', 'Other')], max_length=30),
        ),
    ]
