# Generated by Django 3.2.4 on 2021-06-19 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("member", "0013_auto_20210619_1321"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="architect",
            name="id",
        ),
        migrations.RemoveField(
            model_name="constructor",
            name="id",
        ),
        migrations.RemoveField(
            model_name="education",
            name="id",
        ),
        migrations.AlterField(
            model_name="architect",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="architect",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="constructor",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="constructor",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="education",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
