# Generated by Django 3.2.4 on 2021-06-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_auto_20210624_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='firm',
            field=models.CharField(default=1, max_length=80, verbose_name='Firm'),
            preserve_default=False,
        ),
    ]
