# Generated by Django 3.2.4 on 2021-06-24 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0003_career_firm"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="career",
            name="advert_image",
        ),
    ]
