# Generated by Django 3.2.4 on 2021-06-24 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0004_remove_career_advert_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='career',
            old_name='advert_content',
            new_name='content',
        ),
    ]
